# Generated by Django 2.1 on 2018-09-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180923_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voted_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='voted_users', to='blog.BlogUser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.BlogUser'),
        ),
    ]
