# Generated by Django 2.1 on 2018-10-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180928_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
